export const CATEGORIES = [
  { name: "Event Tickets", icon: "\uD83C\uDFAB" },
  { name: "Graduation Tickets", icon: "\uD83C\uDF93" },
  { name: "Furniture", icon: "\uD83E\uDE91" },
  { name: "Electronics", icon: "\uD83D\uDCBB" },
  { name: "Apartment Subleases", icon: "\uD83C\uDFE0" },
  { name: "Textbooks & Course Materials", icon: "\uD83D\uDCDA" },
  { name: "Clothing & Accessories", icon: "\uD83D\uDC55" },
  { name: "Bikes & Scooters", icon: "\uD83D\uDEB2" },
  { name: "Dorm Essentials", icon: "\uD83D\uDECF\uFE0F" },

  { name: "Tutoring & Services", icon: "\uD83D\uDCDD" },
  { name: "Sports & Fitness Equipment", icon: "\u26BD" },
  { name: "Musical Instruments", icon: "\uD83C\uDFB8" },
  { name: "Jobs & Gigs", icon: "\uD83D\uDCBC" },
  { name: "Travel", icon: "\u2708\uFE0F" },
  { name: "Lab & Art Supplies", icon: "\uD83D\uDD2C" },
  { name: "Gaming", icon: "\uD83C\uDFAE" },
  { name: "Food & Meal Plans", icon: "\uD83C\uDF55" },
  { name: "Other", icon: "\uD83D\uDCE6" },
];
